### ISSUE TITLE
Add @frostbytedata and @venkatakorrapati as collaborators.

### ISSUE THREAD

**Issue by preston** [HII-C/patient_viewer#27]

**Comment by preston** [comment]
@kaaniboy I need to add/drop staff again.. please make sure I'm set as co-owner of the "team" so I can make adjustments at the project level. :)

**Comment by kaaniboy** [comment]
@preston I just sent you an invite to become an owner of the entire organization. Let me know if that works.

**Comment by preston** [comment]
Looks good, thanks..
