### ISSUE TITLE
Create global "Add to Scratchpad"

### ISSUE THREAD

**Issue by kaaniboy** [HII-C/patient_viewer#3]
Implement a global “Add to Scratchpad” button that applies to all three columns at once. Remove old "Add to Scratchpad" button within the individual columns.

There she a global "deselect" button to unselect all checkboxes.

**Comment by steven85048** [comment]
Thank you

**Comment by kaaniboy** [comment]
@rnshah9 You're first task should be adding a new button to the toolbar component that will eventually support adding items to the scratch pad. For now, you do not need to define any functionality. Just modify the view associated with the toolbar component and add a button with an icon (the filter icon from available on the Bootstrap website).

Let me know if you have any questions.

**Comment by rnshah9** [comment]
Finished and pushed.
