### ISSUE TITLE
Create `AllergyIntolerance` for conditions service

### ISSUE THREAD

**Issue by kaaniboy** [HII-C/patient_viewer#32]
Create `AllergyIntolerance` model as per https://www.hl7.org/fhir/allergyintolerance.html. Then, make the `loadAllergies` method in the conditions service return an array of `AllergyIntolerance` rather than raw JSON.

**Comment by mattbudiman** [comment]
I'm currently not able to get the allergies to display properly. This is what my code for the `loadAllergies` method in the conditions service looks like thus far:

> loadAllergies(patient: Patient): Observable<Array<AllergyIntolerance>> {
    var url = this.fhirService.getUrl() + "/AllergyIntolerance" + "?patient=" + patient.id;
    return this.http.get(url, this.fhirService.options(true))
      .map(res => res.json())
      .concatMap(data => {
        let allergies: Array<AllergyIntolerance> = [];
        if (data['entry']) {
          allergies = <Array<AllergyIntolerance>> data.entry.map(r => r['resource']);
        }
        return Observable.of(allergies);
      });
  }

Is this the correct way to cast the JSON into `AllergyIntolerance` objects?

This is how I'm currently loading the allergies into the patient component:

> this.conditionService.loadAllergies(this.patient).subscribe(allergies => {
      this.allergies = allergies.map(allergy => allergy.text);
      // Set displayed allergy string
      if (!this.allergies) { // Patient has no allergies
        this.allergy = "none";
      } else if (this.allergies.length == 1) { // Patient has exactly one allergy
        this.allergy = this.allergies[0];
      } else { // Patient has multiple allergies
        this.allergy = "multiple";
        this.hoverStyling = true;
      }

**Comment by kaaniboy** [comment]
No need to use `concatMap` (that method is only needed if the API response is paginated across multiple requests). The following method in the `carePlan` service is a good example of how the `loadAllergies` method should look:

```
loadCarePlans(patient: Patient): Observable<Array<CarePlan>> {
    let url = this.fhirService.getUrl() + this.path + "?patient=" + patient.id;

    return this.http.get(url, this.fhirService.options(true)).map(res => {
      let json = res.json();

      if (json.entry) {
        return <Array<CarePlan>>json.entry.map(r => r['resource']);
      } else {
        // The patient has no care plans, so return an empty array
        return new Array<CarePlan>();
      }
    });
  }
```

Essentially, the only thing that needs to be changed in the above are the types (from `CarePlan` to `AllergyIntolerance`).

The logic for displaying the allergies seems correct. However, make sure you choose a patient who actually has an allergy from the Sandbox for testing. You can also use `console.log()` statements to check what data is being retrieved.
