### ISSUE TITLE
Complete the Angular Tutorial

### ISSUE THREAD

**Issue by kaaniboy** [HII-C/patient_viewer#5]
Begin going through the Angular tutorial (https://angular.io/tutorial) that is available on the official website.

Please respond to this thread with progress you have made in the tutorial. You can also comment any questions you have as you go through.

**Comment by MattBudiman** [comment]
I am currently on the fourth part of the tutorial (Making a list)

**Comment by rnshah9** [comment]
Also currently on the fourth part.

**Comment by rnshah9** [comment]
Finished making list, now separating into components

**Comment by rnshah9** [comment]
oops

**Comment by rnshah9** [comment]
Separated master and detail components, now adding a service

**Comment by MattBudiman** [comment]
also separated master and detail components, also now adding a service
