### ISSUE TITLE
Show different profile image based on patient gender

### ISSUE THREAD

**Issue by kaaniboy** [HII-C/patient_viewer#8]
Currently, the profile image shown is always female, regardless of the gender of the patient. You should add another profile picture for males, and add functionality to display based on the gender. 

This will require making changes to the `patient.pug` file. You will also need to find a suitable male picture somewhere online. You will also most likely need to use the `ngIf` directive to make a decision of what to display based on the patient's gender.

Let me know if you have any questions. Once you are done commit and push your code to the Github repository.

**Comment by mattbudiman** [comment]
How do I go about actually testing my code? I tried running `ng serve --open` in the patient_viewer directory, but it gave me this error: `Unable to find "@angular/cli" in devDependencies.
`

**Comment by mattbudiman** [comment]
Am I on the right track?
![picture_task](https://user-images.githubusercontent.com/32007404/36290629-7cf4724c-1283-11e8-8859-c3f38058bdf6.png)

**Comment by kaaniboy** [comment]
Yup, it is looking great!

**Comment by mattbudiman** [comment]
Awesome! I ran `git commit -m` and `git push origin master`. Did I properly push my code to the GitHub repository?

**Comment by kaaniboy** [comment]
Yeah you pushed correctly. To test code it's the same process we have been using earlier. You just use grunt --force and then open the App through the sandbox. The server should refresh every time you make a change to the code, though it may take twenty seconds or so.

**Comment by kaaniboy** [comment]
@mattbudiman Great job. Just letting you know that I changed `profile.png` to `female.png` to make the distinction more clear.
